// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/sw5005-sus/ceramicraft-user-mservice/server/repository/model"
)

// UserSessionDAO is an autogenerated mock type for the UserSessionDAO type
type UserSessionDAO struct {
	mock.Mock
}

// DelSession provides a mock function with given fields: ctx, userId
func (_m *UserSessionDAO) DelSession(ctx context.Context, userId int) error {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for DelSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSession provides a mock function with given fields: ctx, userId
func (_m *UserSessionDAO) GetSession(ctx context.Context, userId int) (*model.UserSession, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 *model.UserSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*model.UserSession, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *model.UserSession); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetSession provides a mock function with given fields: ctx, userSession
func (_m *UserSessionDAO) SetSession(ctx context.Context, userSession *model.UserSession) error {
	ret := _m.Called(ctx, userSession)

	if len(ret) == 0 {
		panic("no return value specified for SetSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserSession) error); ok {
		r0 = rf(ctx, userSession)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserSessionDAO creates a new instance of UserSessionDAO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserSessionDAO(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserSessionDAO {
	mock := &UserSessionDAO{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
