services:
  mysql-container:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=user_db
    # Pure memory, disappears when CI ends
    tmpfs: /var/lib/mysql
    networks:
      ci-net:
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_PASSWORD}"]
      interval: 5s
      timeout: 2s
      retries: 5

  kafka-container:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-container
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: ohAxBaI7QUuIq7lQBYzRYA  
    command: >
      bash -c "
        if [ ! -f /var/lib/kafka/data/meta.properties ]; then
          kafka-storage format -t $$CLUSTER_ID -c /etc/kafka/kraft/server.properties;
        fi &&
        kafka-server-start /etc/kafka/kraft/server.properties
      "
    networks: 
      ci-net: 
  ceramicraft-user-mservice:
    build:
      context: ../../server
      dockerfile: Dockerfile
    container_name: ceramicraft-user-mservice
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_EMAIL_FROM=${SMTP_EMAIL_FROM}
      - JWT_SECRET=${JWT_SECRET}
      - ZITADEL_APP_API_KEY={"key":"test-key"}
      - ZITADEL_SERVICE_API_KEY={"key":"test-key"}
    depends_on:
      mysql-container:
        condition: service_healthy
      kafka-container:
        condition: service_started

    networks:
      - ci-net
    ports:
      - "8080:8080"   
    command: ["sh", "-c", "apk add --no-cache netcat-openbsd && chmod +x /app/wait-for.sh && ./wait-for.sh mysql-container 3306 ./main"]
    volumes:
      - ./wait-for.sh:/app/wait-for.sh   # CI only wait-for script
    user: root
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/user-ms/v1/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
networks:
  ci-net: