definitions:
  data.BaseResponse:
    properties:
      code:
        type: integer
      data: {}
      err_msg:
        type: string
    type: object
  data.UserActivateReq:
    properties:
      code:
        maxLength: 6
        minLength: 6
        type: string
    required:
    - code
    type: object
  data.UserAddressVO:
    properties:
      city:
        type: string
      contact_phone:
        type: string
      country:
        type: string
      detail:
        type: string
      first_name:
        type: string
      id:
        type: integer
      is_default:
        type: boolean
      last_name:
        type: string
      province:
        type: string
      user_id:
        type: integer
      zip_code:
        type: string
    required:
    - contact_phone
    - country
    - detail
    - first_name
    - last_name
    - zip_code
    type: object
  data.UserLoginVO:
    properties:
      email:
        type: string
      id:
        type: integer
      password:
        type: string
    required:
    - email
    - password
    type: object
  data.UserProfileVO:
    properties:
      avatar:
        type: string
      default_address:
        $ref: '#/definitions/data.UserAddressVO'
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /user-ms/v1/{client}/login:
    post:
      consumes:
      - application/json
      description: Authenticates a user with their email and password and returns
        a token.
      parameters:
      - description: User login information
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/data.UserLoginVO'
      - description: Client identifier
        enum:
        - customer
        - merchant
        in: path
        name: client
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Login successful, returns auth token in cookie
          schema:
            allOf:
            - $ref: '#/definitions/data.BaseResponse'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/data.BaseResponse'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/data.BaseResponse'
            - properties:
                data:
                  type: string
              type: object
      summary: User Login
      tags:
      - Authentication
  /user-ms/v1/{client}/logout:
    post:
      description: invalidates the user's auth token cookie.
      parameters:
      - description: Client identifier
        enum:
        - customer
        - merchant
        in: path
        name: client
        required: true
        type: string
      responses:
        "200":
          description: Logout successful
          schema:
            allOf:
            - $ref: '#/definitions/data.BaseResponse'
            - properties:
                data:
                  type: string
              type: object
      summary: User Logout
      tags:
      - Authentication
  /user-ms/v1/{client}/users:
    post:
      consumes:
      - application/json
      description: This endpoint allows a new user to register by providing their
        details in JSON format.
      parameters:
      - description: User registration details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/data.UserLoginVO'
      - description: Client identifier
        enum:
        - customer
        - merchant
        in: path
        name: client
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/data.BaseResponse'
      summary: Register a new user
      tags:
      - Register
  /user-ms/v1/{client}/users/activate:
    put:
      consumes:
      - application/json
      description: This endpoint allows a new user to activate by providing their
        verification code in JSON format.
      parameters:
      - description: User activate request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/data.UserActivateReq'
      - description: Client identifier
        enum:
        - customer
        - merchant
        in: path
        name: client
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/data.BaseResponse'
      summary: Activate a new user
      tags:
      - Register
  /user-ms/v1/customer/oauth-callback:
    post:
      consumes:
      - application/json
      description: This endpoint allows a new user to register by Zitadel access_token.
      parameters:
      - description: Insert your access token with 'Bearer ' prefix
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/data.BaseResponse'
      summary: Register a new user authed by Zitadel
      tags:
      - Register
  /user-ms/v1/customer/users/self:
    get:
      consumes:
      - application/json
      description: This endpoint allows current login user fetch his/her profile in
        JSON format.
      produces:
      - application/json
      responses:
        "200":
          description: data is UserProfileVO
          schema:
            $ref: '#/definitions/data.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/data.BaseResponse'
      summary: Get User Profile
      tags:
      - User
    put:
      consumes:
      - application/json
      description: This endpoint allows current login user update his/her profile
        in JSON format.
      parameters:
      - description: User profile to update
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/data.UserProfileVO'
      produces:
      - application/json
      responses:
        "200":
          description: data is UserProfileVO
          schema:
            $ref: '#/definitions/data.BaseResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/data.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/data.BaseResponse'
      summary: Update User Profile
      tags:
      - User
  /user-ms/v1/customer/users/self/addresses:
    get:
      consumes:
      - application/json
      description: This endpoint allows user list all their addresses.
      produces:
      - application/json
      responses:
        "200":
          description: data is []UserAddressVO
          schema:
            $ref: '#/definitions/data.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/data.BaseResponse'
      summary: List User Addresses
      tags:
      - UserAddress
    post:
      consumes:
      - application/json
      description: This endpoint allows user create new address in JSON format.
      parameters:
      - description: user address to create
        in: body
        name: address
        required: true
        schema:
          $ref: '#/definitions/data.UserAddressVO'
      produces:
      - application/json
      responses:
        "201":
          description: data is UserAddressVO
          schema:
            $ref: '#/definitions/data.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/data.BaseResponse'
      summary: Create New User Address
      tags:
      - UserAddress
  /user-ms/v1/customer/users/self/addresses/{address_id}:
    delete:
      consumes:
      - application/json
      description: This endpoint allows user delete their address.
      parameters:
      - description: Address ID
        in: path
        name: address_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/data.BaseResponse'
      summary: Delete User Address
      tags:
      - UserAddress
    put:
      consumes:
      - application/json
      description: This endpoint allows user update their old address in JSON format.
      parameters:
      - description: user address to update
        in: body
        name: address
        required: true
        schema:
          $ref: '#/definitions/data.UserAddressVO'
      produces:
      - application/json
      responses:
        "200":
          description: data is UserAddressVO
          schema:
            $ref: '#/definitions/data.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/data.BaseResponse'
      summary: Update existing User Address
      tags:
      - UserAddress
swagger: "2.0"
