// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	proxy "github.com/sw5005-sus/ceramicraft-user-mservice/server/proxy"
	model "github.com/sw5005-sus/ceramicraft-user-mservice/server/repository/model"
)

// ZitadelProxy is an autogenerated mock type for the ZitadelProxy type
type ZitadelProxy struct {
	mock.Mock
}

// SyncMeta2Zitadel provides a mock function with given fields: ctx, user
func (_m *ZitadelProxy) SyncMeta2Zitadel(ctx context.Context, user *model.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for SyncMeta2Zitadel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateToken provides a mock function with given fields: ctx, tokenStr
func (_m *ZitadelProxy) ValidateToken(ctx context.Context, tokenStr string) (*proxy.AuthUser, error) {
	ret := _m.Called(ctx, tokenStr)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *proxy.AuthUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*proxy.AuthUser, error)); ok {
		return rf(ctx, tokenStr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *proxy.AuthUser); ok {
		r0 = rf(ctx, tokenStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proxy.AuthUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyTokenWithBackendIdentity provides a mock function with given fields: ctx, accessToken
func (_m *ZitadelProxy) VerifyTokenWithBackendIdentity(ctx context.Context, accessToken string) (*model.User, error) {
	ret := _m.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for VerifyTokenWithBackendIdentity")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return rf(ctx, accessToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = rf(ctx, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewZitadelProxy creates a new instance of ZitadelProxy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewZitadelProxy(t interface {
	mock.TestingT
	Cleanup(func())
}) *ZitadelProxy {
	mock := &ZitadelProxy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
