name: Build & Trivy Scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Prepare Image Metadata
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "SCAN_TAG=${REPO_OWNER}/user-ms:${{ github.sha }}" >> $GITHUB_ENV

      - name: Build image
        run: |
          docker build -t ${{ env.SCAN_TAG }} server/

      # scan and block if high severity vulnerabilities found
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.SCAN_TAG }}
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'          # non zero exit code if vulnerabilities found
          ignore-unfixed: true    # ignore unfixed vulnerabilities